"""Fix awkward Korean-English mixed terms in survey_ko.md — go full English for technical terms."""

import re
from pathlib import Path

p = Path(__file__).parent / "survey_ko.md"
text = p.read_text(encoding="utf-8")

replacements = [
    # Section titles — keep structure Korean but technical terms English
    ("힘 인식 VLA", "Force-aware VLA"),
    ("Tactile VLA", "Tactile VLA"),
    ("VLM 안내 Impedance 제어", "VLM-guided Impedance Control"),
    ("학습된 impedance / 가변 compliance 제어", "Learned Impedance / Variable Compliance Control"),
    ("VLA 기반 모델: 버전 이력", "VLA Foundation Models: Version History"),
    ("RL 기반 Dexterous Manipulation", "RL-based Dexterous Manipulation"),
    ("비전-언어-행동", "Vision-Language-Action"),
    ("비전-운동 정책 (언어 조건부 없음)", "Visuomotor Policies (without language conditioning)"),
    ("비전-운동 정책", "Visuomotor Policies"),

    # Column headers — full English
    ("논문", "Paper"),
    ("연구 그룹", "Group"),
    ("학회", "Venue"),
    ("연도", "Year"),
    ("핸드 (자유도)", "Hand (DoF)"),
    ("작업", "Tasks"),
    ("코드", "Code"),
    ("가중치", "Weights"),
    ("핵심 방법", "Key Method"),
    ("핵심 특징", "Key Feature"),
    ("힘 입력", "Force Input"),
    ("로봇", "Robot"),
    ("시뮬레이션", "Sim"),
    ("객체", "Objects"),
    ("학습 방법", "Learning Method"),
    ("오픈 코드", "Open Code"),
    ("오픈 가중치", "Open Weights"),
    ("버전", "Version"),
    ("날짜", "Date"),
    ("파라미터", "Params"),
    ("행동 헤드", "Action Head"),
    ("디코더", "decoder"),
    ("비용", "Cost"),
    ("센서 유형", "Sensor Type"),
    ("데이터 규모", "Scale"),
    ("핸드 유형", "Hand Type"),
    ("포맷", "Format"),
    ("모달리티", "Modality"),
    ("입력", "Input"),
    ("대상 핸드", "Target Hand"),
    ("힘 피드백", "Force Feedback"),
    ("설계 파일", "Design Files"),

    # Technical terms in descriptions
    ("행동 공간", "action space"),
    ("행동 청킹", "action chunking"),
    ("자기회귀", "autoregressive"),
    ("사전학습", "pretraining"),
    ("자기중심", "egocentric"),
    ("이중 수준 최적화", "bilevel optimization"),
    ("지도학습", "supervised"),
    ("목표 조건부", "goal-conditioned"),
    ("하이브리드", "hybrid"),
    ("미문서화", "not documented"),
    ("미보고", "not reported"),
    ("관절 토크", "joint torque"),
    ("서보 전류", "servo current"),
    ("잔차 보정", "residual correction"),
    ("보조 토크 예측", "auxiliary torque prediction"),
    ("수동 조정", "hand-tuned"),
    ("힘 목표", "force targets"),
    ("에너지 기반", "energy-based"),
    ("인코더만", "encoder only"),
    ("성공 예측기", "success predictor"),
    ("접촉 모델", "contact model"),
    ("위치만", "position only"),
    ("프로젝트 페이지만", "project page only"),
    ("프로젝트 페이지 (준비 중)", "project page (pending)"),
    ("비상업용", "non-commercial"),
    ("상업용 허용", "commercial OK"),
    ("공식 미공개", "not officially released"),
    ("서드파티 재구현 존재", "third-party reimplementations exist"),
    ("미공개", "not released"),
    ("미지정", "not specified"),
    ("미확인", "not verified"),
    ("학습 불필요", "training-free"),
    ("실제 하드웨어", "real hardware"),
    ("실제만", "real only"),
    ("코드만", "code only"),
    ("데이터셋만", "dataset only"),
    ("라이선스", "license"),
    ("부분적", "partial"),
    ("고정 K", "fixed K"),
    ("고정 B", "fixed B"),
    ("고정", "fixed"),
    ("렌치-위치", "wrench-position"),
    ("위치-힘", "position-force"),
    ("스칼라 stiffness", "scalar stiffness"),
    ("EE stiffness", "EE stiffness"),
    ("리타겟팅된 인간 시연", "retargeted human demos"),
    ("관절 객체", "articulated objects"),
    ("관절 manipulation", "articulated manipulation"),
    ("관절 위치", "joint position"),
    ("렌치", "wrench"),
    ("카테고리 수준 신규", "category-level novel"),
    ("다중 전략", "multi-strategy"),
    ("이종 임바디먼트", "heterogeneous embodiment"),
    ("인지-행동 분리", "cognition-action separation"),
    ("적응형 행동 그리드", "adaptive action grids"),
    ("범용 행동 코드북", "universal action codebook"),
    ("월드 모델", "world model"),
    ("힘 도메인", "force-domain"),
    ("grasp력", "grip force"),
    ("힘 예측", "force prediction"),
    ("예측 힘", "predicted force"),
    ("캡처된 상호작용", "captured interaction"),

    # pi family specific
    ("2단계: FAST 사전학습 →", "two-stage: FAST pretrain →"),
    ("이중", "dual"),

    # Misc
    ("비전 전용 대비", "vs vision-only"),
    ("최대 규모 오픈 diffusion 모델", "largest open diffusion model"),
    ("모듈형", "modular"),
    ("병렬 디코딩", "parallel decoding"),
    ("다양한 핸드 대상 설계", "designed for diverse embodiments"),
]

for old, new in replacements:
    text = text.replace(old, new)

p.write_text(text, encoding="utf-8")
print("Done - fixed Korean terminology")
